// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwUvaCqXQo0Pxduziir63SiLIIqvhrxso',
    appId: '1:365887153225:web:70ee612c9024a60cc90b98',
    messagingSenderId: '365887153225',
    projectId: 'ekonnectapp',
    authDomain: 'ekonnectapp.firebaseapp.com',
    storageBucket: 'ekonnectapp.firebasestorage.app',
    measurementId: 'G-S1N2K1YVK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWZNqPl2Tvg7Zz8NXvuD0E86wPRJi2DQc',
    appId: '1:365887153225:android:dc779b7cc79511e9c90b98',
    messagingSenderId: '365887153225',
    projectId: 'ekonnectapp',
    storageBucket: 'ekonnectapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL5cfnRT3A_BQqmp14FrQooZeQI-sVxWc',
    appId: '1:365887153225:ios:a994351e81ef8347c90b98',
    messagingSenderId: '365887153225',
    projectId: 'ekonnectapp',
    storageBucket: 'ekonnectapp.firebasestorage.app',
    iosBundleId: 'ke.co.tafiti.ekonnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL5cfnRT3A_BQqmp14FrQooZeQI-sVxWc',
    appId: '1:365887153225:ios:a994351e81ef8347c90b98',
    messagingSenderId: '365887153225',
    projectId: 'ekonnectapp',
    storageBucket: 'ekonnectapp.firebasestorage.app',
    iosBundleId: 'ke.co.tafiti.ekonnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwUvaCqXQo0Pxduziir63SiLIIqvhrxso',
    appId: '1:365887153225:web:c18a6e58fd0e65dfc90b98',
    messagingSenderId: '365887153225',
    projectId: 'ekonnectapp',
    authDomain: 'ekonnectapp.firebaseapp.com',
    storageBucket: 'ekonnectapp.firebasestorage.app',
    measurementId: 'G-KZYLKWVHT0',
  );
}
